# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14AtEdOHUMaa9-3VpjuUBC1K8eipBTJGI
"""

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

def fill_all_missing_values(data):
    '''Def to fill all missing values
    
    Params:
        data train

    Returns:
        DataFrame with all missing values filled in
    '''
    for col in data.columns:
        if data[col].dtype in ('int64','float64'):
            data[col].fillna(data[col].mean(), inplace=True)
        else:
            data[col].fillna(data[col].mode()[0], inplace=True)

def encode_catagorical_columns(train, test, level_col):
    '''Def to encode catagorical columns
    
    Params:
        train: train data
        test: test data

    Returns:
        DataFrame with encode catagorical columns
    '''
    encoder = LabelEncoder()
    for col in Level_col:
        train[col] = encoder.fit_transform(train[col])
        test[col]  = encoder.transform(test[col])